### ISSUE TITLE
TimePickerDialog.show(getSupportFragmentManager(), "timepicker"); CRASH

### ISSUE THREAD

**Issue by KrasimirVasilev** [flavienlaurent/datetimepicker#23]
java.lang.NullPointerException
            at com.sleepbot.datetimepicker.time.TimePickerDialog.onCreateView(TimePickerDialog.java:194)
            at android.support.v4.app.Fragment.performCreateView(Fragment.java:1478)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:928)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1105)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:682)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1461)
            at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:440)
            at android.os.Handler.handleCallback(Handler.java:725)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5041)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by edisonw** [comment]
Have you modified the code? It can't crash on line 194...

```
    mMinutePickerDescription = res.getString(R.string.minute_picker_description);
```

Because 193 ensures that res/R.string are both not null. 

ref: https://github.com/flavienlaurent/datetimepicker/blob/master/datetimepicker-library/src/com/sleepbot/datetimepicker/time/TimePickerDialog.java

**Comment by flavienlaurent** [comment]
@KrasimirVasilev if you have this problem again, give use more informations. Thanks
