### ISSUE TITLE
time picker crashes on device with API level 14

### ISSUE THREAD

**Issue by alirezabonab** [flavienlaurent/datetimepicker#45]
when touching hour in timepicker it crashes and says 
"RadialTextView was not ready for animation."
because mDrawValuesReady is false and mReappearAnimator is null in getReappearAnimator() , i think it's because onDraw method for minutes RadialTextsView does not raise when timepickerdialog shows in API 14 and i dont know why , it is so strange cause it runs on other APIs.

05-05 17:01:38.631    3038-3038/com.x.y E/RadialTextsView﹕ RadialTextView was not ready for animation.
05-05 17:01:38.631    3038-3038/com.x.y E/RadialSelectorView﹕ RadialSelectorView was not ready for animation.
05-05 17:01:38.729    3038-3038/com.x.y E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.IllegalStateException: Circular dependencies cannot exist in AnimatorSet
            at com.nineoldandroids.animation.AnimatorSet.sortNodes(AnimatorSet.java:818)
            at com.nineoldandroids.animation.AnimatorSet.start(AnimatorSet.java:456)
            at com.sleepbot.datetimepicker.time.RadialPickerLayout.setCurrentItemShowing(RadialPickerLayout.java:559)
            at com.sleepbot.datetimepicker.time.TimePickerDialog.setCurrentItemShowing(TimePickerDialog.java:421)
            at com.sleepbot.datetimepicker.time.TimePickerDialog.onValueSelected(TimePickerDialog.java:369)
            at com.sleepbot.datetimepicker.time.RadialPickerLayout.onTouch(RadialPickerLayout.java:734)
            at android.view.View.dispatchTouchEvent(View.java:5481)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1953)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1714)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1959)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1728)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1959)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1728)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1959)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1728)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1959)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1728)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1959)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1728)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1892)
            at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1371)
            at android.app.Dialog.dispatchTouchEvent(Dialog.java:725)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1840)
            at android.view.View.dispatchPointerEvent(View.java:5662)
            at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:2863)
            at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2442)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4340)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by alirezabonab** [comment]
sample apk also have the same problem

**Comment by flavienlaurent** [comment]
In code there is a check about that

```
//NineOldDroids does not work in this case due to denepency recursion. 
animate = animate && Build.VERSION.SDK_INT >= 14; 
```

Maybe, @edisonw could throw some light on what's going on.

**Comment by alirezabonab** [comment]
but only in API level 14 this happens and under 14 for example in 13 does not happen .
it is big question to me why this happening ,
please check it with emulator on API level 14 and 13.

thanks for reply.

**Comment by edisonw** [comment]
um..interesting. yea @flavienlaurent is right that the animation should not happen in 13, in 14 NineOldDroids should have fell back to the SDK implementation of the animation and not throw that tho..

**Comment by AlessandroLucchet** [comment]
As I wrote <a href="https://github.com/code-troopers/android-betterpickers/issues/96">here</a>, I found a fix for that.
you had to add this check in the setCurrentItemShowing function of RadialPickerLayout:
`if(anims[0]!=null&&anims[1]!=null&&anims[2]!=null&&anims[3]!=null)`

here is the code:

```
if(anims[0]!=null&&anims[1]!=null&&anims[2]!=null&&anims[3]!=null) {
    if (mTransition != null && mTransition.isRunning()) {
        mTransition.end();
    }
    mTransition = new AnimatorSet();
    mTransition.playTogether(anims);
    mTransition.start();
}else{
    int hourAlpha = (index == HOUR_INDEX) ? 1 : 0;
    int minuteAlpha = (index == MINUTE_INDEX) ? 1 : 0;
    mHourRadialTextsView.setAlpha(hourAlpha);
    mHourRadialSelectorView.setAlpha(hourAlpha);
    mMinuteRadialTextsView.setAlpha(minuteAlpha);
    mMinuteRadialSelectorView.setAlpha(minuteAlpha);
}
```

it looks like in some device (Android 3.x and 4.0),mMinuteRadialTextsView and mMinuteRadialSelectorView are drawn only after getReappearAnimator() is called.
With this check, I fixed it
