### ISSUE TITLE
Time picker dialog crash!

### ISSUE THREAD

**Issue by naz013** [flavienlaurent/datetimepicker#51]
When call show time picker dialog crash on line 193:

view.findViewById(R.id.time_picker_dialog).setOnKeyListener(keyboardListener);

with error:

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setOnKeyListener(android.view.View$OnKeyListener)' on a null object reference
            at com.sleepbot.datetimepicker.time.TimePickerDialog.onCreateView(TimePickerDialog.java:193)
            at android.support.v4.app.Fragment.performCreateView(Fragment.java:1504)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:942)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1121)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:682)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1484)
            at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:450)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5001)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601).

**Comment by flavienlaurent** [comment]
It crashes every time ?

**Comment by naz013** [comment]
Yes, every time when call to show.

**Comment by manpreetpatil** [comment]
Please help me I'm also getting same issue. I have fixed the #51 but no luck . Please help me .

**Comment by matthewrice345** [comment]
This issue still exists in 0.0.2

**Comment by manpreetpatil** [comment]
I have found the issue ...it was at my end.. My xml tag id was conflicting  with lib xml ids.
