### ISSUE TITLE
Crash on Froyo

### ISSUE THREAD

**Issue by xarlotie** [flavienlaurent/datetimepicker#54]
DatePickerDialog crashes on devices running froyo. Here's the crash log

FATAL EXCEPTION: main
java.lang.NoClassDefFoundError: android.animation.Keyframe
    at com.fourmob.datetimepicker.Utils.getPulseAnimator(Utils.java:41)
    at com.fourmob.datetimepicker.date.DatePickerDialog.setCurrentView(DatePickerDialog.java:124)
    at com.fourmob.datetimepicker.date.DatePickerDialog.onCreateView(DatePickerDialog.java:307)
    at android.support.v4.app.Fragment.performCreateView(Fragment.java:1500)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:938)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1115)
    at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:682)
    at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1478)
    at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:446)
    at android.os.Handler.handleCallback(Handler.java:587)
    at android.os.Handler.dispatchMessage(Handler.java:92)
    at android.os.Looper.loop(Looper.java:144)
    at android.app.ActivityThread.main(ActivityThread.java:4937)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:521)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
    at dalvik.system.NativeStart.main(Native Method)

**Comment by flavienlaurent** [comment]
You changed import statements.

https://github.com/flavienlaurent/datetimepicker/blob/master/datetimepicker-library/src/com/fourmob/datetimepicker/Utils.java#L8

**Comment by xarlotie** [comment]
Yes, I figured. Thanks for the quick response anyways.
