### ISSUE TITLE
Crash on Nexus S with Android 4.1.2

### ISSUE THREAD

**Issue by firegloves** [flavienlaurent/datetimepicker#79]
Hello, i'm tryng to use your beautiful library in my app, but if i launch it on a Nexus S with Android 4.1.2, when i go to open the datepicker the app crashes with this stacktrace:

10-24 13:17:30.882: E/AndroidRuntime(3046): java.lang.NullPointerException
10-24 13:17:30.882: E/AndroidRuntime(3046):     at com.fourmob.datetimepicker.date.DatePickerDialog.onCreateView(DatePickerDialog.java:263)
10-24 13:17:30.882: E/AndroidRuntime(3046):     at android.support.v4.app.Fragment.performCreateView(Fragment.java:1500)
10-24 13:17:30.882: E/AndroidRuntime(3046):     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:938)
10-24 13:17:30.882: E/AndroidRuntime(3046):     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1115)
10-24 13:17:30.882: E/AndroidRuntime(3046):     at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:682)
10-24 13:17:30.882: E/AndroidRuntime(3046):     at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1478)
10-24 13:17:30.882: E/AndroidRuntime(3046):     at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:446)
10-24 13:17:30.882: E/AndroidRuntime(3046):     at android.os.Handler.handleCallback(Handler.java:615)
10-24 13:17:30.882: E/AndroidRuntime(3046):     at android.os.Handler.dispatchMessage(Handler.java:92)
10-24 13:17:30.882: E/AndroidRuntime(3046):     at android.os.Looper.loop(Looper.java:137)
10-24 13:17:30.882: E/AndroidRuntime(3046):     at android.app.ActivityThread.main(ActivityThread.java:4745)
10-24 13:17:30.882: E/AndroidRuntime(3046):     at java.lang.reflect.Method.invokeNative(Native Method)
10-24 13:17:30.882: E/AndroidRuntime(3046):     at java.lang.reflect.Method.invoke(Method.java:511)
10-24 13:17:30.882: E/AndroidRuntime(3046):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
10-24 13:17:30.882: E/AndroidRuntime(3046):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
10-24 13:17:30.882: E/AndroidRuntime(3046):     at dalvik.system.NativeStart.main(Native Method)

Have you any idea?

Thanks
## 

michelangelo

**Comment by toddmo** [comment]
I emulated Nexus S with API 21 and time picker crashed when I clicked on anything in the dialog. Setting vibrate = false fixed it. I can't debug your issue, just sharing what happened in my case.
